services:
  - type: web
    name: MYWEB
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn MYWEB.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: animeweb.settings
      - key: PYTHON_VERSION
        value: 3.9